import type { NextPage } from "next";
import Head from "next/head";
import useTrendingCollections from "../lib/hooks/useTrendingCollections";
import { TrendingCollections } from "../components/TrendingCollections";
import Link from "next/link";
import { AnchorText } from "../components/AnchorText";

const Home: NextPage = () => {
  const { loading, trendingCollections } = useTrendingCollections();
  return (
    <div className="bg-neutral-100 p-16">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto max-w-screen-lg">
        <div className="text-center mb-8">
          This page fetches the trending collection data on the client side.{" "}
          <Link href="/ssr-enabled">
            <AnchorText>Click here</AnchorText>
          </Link>{" "}
          to view the page that renders the same data via SSR
        </div>
        <TrendingCollections
          trendingCollections={trendingCollections}
          loading={loading}
        />
      </main>
    </div>
  );
};

export default Home;
