import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { Contract } from "../components/Contract";
import client from "../lib/apollo-client";
import {
  ERC721Contract,
  TrendingCollectionsQueryResult,
} from "../models/trending-collections";
import { GET_TRENDING_COLLECTIONS } from "../graphql/getTrendingCollectionsQuery";
import { TrendingCollections } from "../components/TrendingCollections";
import Link from "next/link";
import { AnchorText } from "../components/AnchorText";

interface Props {
  trendingCollections: ERC721Contract[];
}

const SsrEnabled: NextPage<Props> = ({ trendingCollections }) => {
  return (
    <div className="bg-neutral-100 p-16">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto max-w-screen-lg">
        <div className="text-center mb-8">
          This page renders the trending collection data on using SSR.{" "}
          <Link href="/">
            <AnchorText>Click here</AnchorText>
          </Link>{" "}
          to view the page that fetches the same data on the client side.
        </div>
        <TrendingCollections trendingCollections={trendingCollections} />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await client.query<TrendingCollectionsQueryResult>({
    query: GET_TRENDING_COLLECTIONS,
  });

  return {
    props: {
      trendingCollections: data.data.trendingCollections.edges.map(
        (edge) => edge.node
      ),
    },
  };
};

export default SsrEnabled;
